<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MealPlanner.SharedKernel\MealPlanner.SharedKernel.csproj" />
    <ProjectReference Include="..\MealService.Domain\MealService.Domain.csproj" />
  </ItemGroup>

</Project>
